### ISSUE TITLE
trunc

### ISSUE THREAD

**Issue by melsman** [henrikurms/tail2futhark#3]
When typing "make all" in the test/benchmark directory, the tail2futhark compiler translates successfully the eacheaster.tail program into a file eacheaster.fut file, but it seems to reference a function `trunc`, which is not in scope:

```
make all
...
~/gits/apltail/aplt -p_types -p_tail -silent -c -o eacheaster.tail ~/gits/apltail/lib/prelude.apl eacheaster.apl 
Wrote file eacheaster.tail
~/gits/tail2futhark/dist/build/tail2futhark/tail2futhark -o eacheaster.fut eacheaster.tail 
futhark-c -o fut_eacheaster eacheaster.fut
Unknown function trunc called at eacheaster.fut:123:58-123:58.
```

Maybe the futhark compiler changed?!

```
bash-3.2$ futhark-c -v
Futhark 0.1
(C) HIPERFIT research centre
Department of Computer Science, University of Copenhagen (DIKU) 
```

**Comment by athas** [comment]
Martin Elsman notifications@github.com writes:

> When typing "make all" in the test/benchmark directory, the
> tail2futhark compiler translates successfully the eacheaster.tail
> program into a file eacheaster.fut file, but it seems to reference a
> function `trunc`, which is not in scope:
> 
> ```
> make all
> ...
> ~/gits/apltail/aplt -p_types -p_tail -silent -c -o eacheaster.tail
> ```
> 
> ~/gits/apltail/lib/prelude.apl eacheaster.apl
>     Wrote file eacheaster.tail
>     ~/gits/tail2futhark/dist/build/tail2futhark/tail2futhark -o eacheaster.fut eacheaster.tail 
>     futhark-c -o fut_eacheaster eacheaster.fut
>     Unknown function trunc called at eacheaster.fut:123:58-123:58.
> 
> Maybe the futhark compiler changed?!

Yes. significantly.  I'm cleaning things up - will take a look at this.

## 

\  Troels
/\ Henriksen
